version: '2'

services:
  app:
    image: 'test5:latest'
    build:
      context: .
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/task5
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
  db:
    image: 'postgres:latest'
    container_name: db
    environment:
      - POSTGRES_DB=task5
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
